# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\dev\cv\uidesigns\comparison_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComparisonDialog(object):
    def setupUi(self, ComparisonDialog):
        ComparisonDialog.setObjectName("ComparisonDialog")
        ComparisonDialog.resize(1217, 883)
        ComparisonDialog.setStyleSheet("QDialog {\n"
"    background-color: #f5f7fa;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-weight: 600;\n"
"    font-size: 11pt;\n"
"    color: #2d3748;\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 8px;\n"
"    margin-top: 12px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 10px 0 10px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    padding: 12px;\n"
"    font-family: \'Monaco\', \'Menlo\', \'Ubuntu Mono\', monospace;\n"
"    font-size: 9pt;\n"
"    line-height: 1.4;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    gridline-color: #e2e8f0;\n"
"    font-size: 9pt;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px 12px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #ebf8ff;\n"
"    color: #2d3748;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f7fafc;\n"
"    border: none;\n"
"    border-bottom: 2px solid #4299e1;\n"
"    padding: 8px 12px;\n"
"    font-weight: 600;\n"
"    color: #4a5568;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1.5px solid #e2e8f0;\n"
"    color: #4a5568;\n"
"    padding: 10px 16px;\n"
"    border-radius: 6px;\n"
"    min-height: 36px;\n"
"    font-size: 10pt;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f7fafc;\n"
"    border-color: #cbd5e0;\n"
"}\n"
"\n"
"QPushButton#exportBtn {\n"
"    background-color: #9f7aea;\n"
"    border-color: #9f7aea;\n"
"    color: #ffffff;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton#exportBtn:hover {\n"
"    background-color: #805ad5;\n"
"    border-color: #805ad5;\n"
"}\n"
"\n"
"QLabel#hubble001Label {\n"
"    font-size: 12pt;\n"
"    font-weight: 700;\n"
"    color: #2d3748;\n"
"    padding: 8px;\n"
"    background: linear-gradient(to right, #ebf8ff, #ffffff);\n"
"    border-radius: 6px;\n"
"    border: 2px solid #4299e1;\n"
"}\n"
"\n"
"QLabel#hubble002Label {\n"
"    font-size: 12pt;\n"
"    font-weight: 700;\n"
"    color: #2d3748;\n"
"    padding: 8px;\n"
"    background: linear-gradient(to right, #faf5ff, #ffffff);\n"
"    border-radius: 6px;\n"
"    border: 2px solid #9f7aea;\n"
"}\n"
"\n"
"QLabel#winnerLabel {\n"
"    font-size: 13pt;\n"
"    font-weight: 800;\n"
"    color: #2d3748;\n"
"    padding: 12px;\n"
"    background-color: #f0fff4;\n"
"    border-radius: 8px;\n"
"    border: 3px solid #48bb78;\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"    background-color: #e2e8f0;\n"
"    width: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"    background-color: #cbd5e0;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ComparisonDialog)
        self.verticalLayout.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(ComparisonDialog)
        self.titleLabel.setStyleSheet("font-size: 14pt; font-weight: 700; color: #2d3748; padding-bottom: 8px; border-bottom: 3px solid #9f7aea;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.mainSplitter = QtWidgets.QSplitter(ComparisonDialog)
        self.mainSplitter.setOrientation(QtCore.Qt.Vertical)
        self.mainSplitter.setObjectName("mainSplitter")
        self.imageComparisonWidget = QtWidgets.QWidget(self.mainSplitter)
        self.imageComparisonWidget.setObjectName("imageComparisonWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.imageComparisonWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imageComparisonLabel = QtWidgets.QLabel(self.imageComparisonWidget)
        self.imageComparisonLabel.setStyleSheet("font-size: 11pt; font-weight: 600; color: #4a5568;")
        self.imageComparisonLabel.setObjectName("imageComparisonLabel")
        self.verticalLayout_2.addWidget(self.imageComparisonLabel)
        self.imageSplitter = QtWidgets.QSplitter(self.imageComparisonWidget)
        self.imageSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.imageSplitter.setObjectName("imageSplitter")
        self.hubble001Widget = QtWidgets.QWidget(self.imageSplitter)
        self.hubble001Widget.setObjectName("hubble001Widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.hubble001Widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hubble001Label = QtWidgets.QLabel(self.hubble001Widget)
        self.hubble001Label.setAlignment(QtCore.Qt.AlignCenter)
        self.hubble001Label.setObjectName("hubble001Label")
        self.verticalLayout_3.addWidget(self.hubble001Label)
        self.hubble001View = QtWidgets.QGraphicsView(self.hubble001Widget)
        self.hubble001View.setMinimumSize(QtCore.QSize(400, 300))
        self.hubble001View.setObjectName("hubble001View")
        self.verticalLayout_3.addWidget(self.hubble001View)
        self.hubble001TimeLabel = QtWidgets.QLabel(self.hubble001Widget)
        self.hubble001TimeLabel.setStyleSheet("font-size: 9pt; color: #718096; font-weight: 500;")
        self.hubble001TimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hubble001TimeLabel.setObjectName("hubble001TimeLabel")
        self.verticalLayout_3.addWidget(self.hubble001TimeLabel)
        self.hubble002Widget = QtWidgets.QWidget(self.imageSplitter)
        self.hubble002Widget.setObjectName("hubble002Widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.hubble002Widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hubble002Label = QtWidgets.QLabel(self.hubble002Widget)
        self.hubble002Label.setAlignment(QtCore.Qt.AlignCenter)
        self.hubble002Label.setObjectName("hubble002Label")
        self.verticalLayout_4.addWidget(self.hubble002Label)
        self.hubble002View = QtWidgets.QGraphicsView(self.hubble002Widget)
        self.hubble002View.setMinimumSize(QtCore.QSize(400, 300))
        self.hubble002View.setObjectName("hubble002View")
        self.verticalLayout_4.addWidget(self.hubble002View)
        self.hubble002TimeLabel = QtWidgets.QLabel(self.hubble002Widget)
        self.hubble002TimeLabel.setStyleSheet("font-size: 9pt; color: #718096; font-weight: 500;")
        self.hubble002TimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hubble002TimeLabel.setObjectName("hubble002TimeLabel")
        self.verticalLayout_4.addWidget(self.hubble002TimeLabel)
        self.verticalLayout_2.addWidget(self.imageSplitter)
        self.metricsWidget = QtWidgets.QWidget(self.mainSplitter)
        self.metricsWidget.setObjectName("metricsWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.metricsWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.metricsSplitter = QtWidgets.QSplitter(self.metricsWidget)
        self.metricsSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.metricsSplitter.setObjectName("metricsSplitter")
        self.performanceWidget = QtWidgets.QWidget(self.metricsSplitter)
        self.performanceWidget.setObjectName("performanceWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.performanceWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.performanceLabel = QtWidgets.QLabel(self.performanceWidget)
        self.performanceLabel.setStyleSheet("font-size: 11pt; font-weight: 600; color: #4a5568;")
        self.performanceLabel.setObjectName("performanceLabel")
        self.verticalLayout_6.addWidget(self.performanceLabel)
        self.metricsTable = QtWidgets.QTableWidget(self.performanceWidget)
        self.metricsTable.setRowCount(2)
        self.metricsTable.setColumnCount(6)
        self.metricsTable.setObjectName("metricsTable")
        self.verticalLayout_6.addWidget(self.metricsTable)
        self.analysisWidget = QtWidgets.QWidget(self.metricsSplitter)
        self.analysisWidget.setObjectName("analysisWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.analysisWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.analysisReportLabel = QtWidgets.QLabel(self.analysisWidget)
        self.analysisReportLabel.setStyleSheet("font-size: 11pt; font-weight: 600; color: #4a5568;")
        self.analysisReportLabel.setObjectName("analysisReportLabel")
        self.verticalLayout_7.addWidget(self.analysisReportLabel)
        self.analysisText = QtWidgets.QTextEdit(self.analysisWidget)
        self.analysisText.setReadOnly(True)
        self.analysisText.setObjectName("analysisText")
        self.verticalLayout_7.addWidget(self.analysisText)
        self.verticalLayout_5.addWidget(self.metricsSplitter)
        self.winnerLabel = QtWidgets.QLabel(self.metricsWidget)
        self.winnerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.winnerLabel.setObjectName("winnerLabel")
        self.verticalLayout_5.addWidget(self.winnerLabel)
        self.verticalLayout.addWidget(self.mainSplitter)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(12)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.exportBtn = QtWidgets.QPushButton(ComparisonDialog)
        self.exportBtn.setObjectName("exportBtn")
        self.buttonLayout.addWidget(self.exportBtn)
        self.closeBtn = QtWidgets.QPushButton(ComparisonDialog)
        self.closeBtn.setObjectName("closeBtn")
        self.buttonLayout.addWidget(self.closeBtn)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(ComparisonDialog)
        QtCore.QMetaObject.connectSlotsByName(ComparisonDialog)

    def retranslateUi(self, ComparisonDialog):
        _translate = QtCore.QCoreApplication.translate
        ComparisonDialog.setWindowTitle(_translate("ComparisonDialog", "Algorithm Comparison - Hubble 001 vs Hubble 002"))
        self.titleLabel.setText(_translate("ComparisonDialog", "Comparative Analysis: Hubble 001 (Sequential) vs Hubble 002 (Bulk)"))
        self.imageComparisonLabel.setText(_translate("ComparisonDialog", "Visual Comparison"))
        self.hubble001Label.setText(_translate("ComparisonDialog", "Hubble 001 (Sequential Processing)"))
        self.hubble001TimeLabel.setText(_translate("ComparisonDialog", "Time: --"))
        self.hubble002Label.setText(_translate("ComparisonDialog", "Hubble 002 (Bulk Processing)"))
        self.hubble002TimeLabel.setText(_translate("ComparisonDialog", "Time: --"))
        self.performanceLabel.setText(_translate("ComparisonDialog", "Performance Metrics"))
        self.analysisReportLabel.setText(_translate("ComparisonDialog", "Detailed Analysis Report"))
        self.winnerLabel.setText(_translate("ComparisonDialog", "Overall Winner: --"))
        self.exportBtn.setText(_translate("ComparisonDialog", "Export Report"))
        self.closeBtn.setText(_translate("ComparisonDialog", "Close"))
