# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\dev\cv\uidesigns\filters_tools_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FiltersTool(object):
    def setupUi(self, FiltersTool):
        FiltersTool.setObjectName("FiltersTool")
        FiltersTool.resize(288, 253)
        self.gridLayout = QtWidgets.QGridLayout(FiltersTool)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 1, 1)

        self.retranslateUi(FiltersTool)
        QtCore.QMetaObject.connectSlotsByName(FiltersTool)

    def retranslateUi(self, FiltersTool):
        _translate = QtCore.QCoreApplication.translate
        FiltersTool.setWindowTitle(_translate("FiltersTool", "Filters Tool"))
