# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\dev\cv\uidesigns\main_window_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageLab(object):
    def setupUi(self, ImageLab):
        ImageLab.setObjectName("ImageLab")
        ImageLab.resize(806, 686)
        ImageLab.setStyleSheet("/* --- GLOBAL STYLES (QApplication and Main Window) --- */\n"
"QMainWindow, QWidget {\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    color: #1e1e1e; /* Dark text color */\n"
"    font-family: \"Segoe UI\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"/* --- HEADER BAR (If using a QToolBar) --- */\n"
"QToolBar {\n"
"    background-color: #e6e6e6;\n"
"    border: none;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QStackedWidget {\n"
"    background-color: #f0f0f0;\n"
"    border: 0.5px solid #e0e0e0;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #c0c0c0;\n"
"    padding: 10px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"/* --- SIDEBAR & TOOL BUTTONS (Left Panel) --- */\n"
"/* The main sidebar area */\n"
"QDockWidget {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: none;\n"
"}\n"
"QDockWidget::title {\n"
"    padding: 5px;\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"/* Tool Buttons in the sidebar */\n"
"QPushButton {\n"
"    /* Base style for all buttons */\n"
"    background-color: #e0e0e0;\n"
"    border: 1px solid #cccccc;\n"
"    color: #1e1e1e;\n"
"    padding: 8px 15px;\n"
"    border-radius: 4px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"/* Hover and Click effects for buttons */\n"
"QPushButton:hover {\n"
"    background-color: #d4d4d4;\n"
"}\n"
"/* Selected tool/active state in sidebar */\n"
"QPushButton:checked, QPushButton:pressed {\n"
"    background-color: #0078d4; /* Accent color - Royal Blue */\n"
"    border-color: #0078d4;\n"
"    color: #ffffff; /* White text on accent */\n"
"}\n"
"\n"
"/* Specific styling for the large \"Upload Image\" button */\n"
"QPushButton#UploadButton { \n"
"    background-color: #009688; /* Teal accent */\n"
"    border-color: #009688;\n"
"    color: #ffffff; /* White text for high visibility */\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"QPushButton#UploadButton:hover {\n"
"    background-color: #00bfa5;\n"
"}\n"
"\n"
"/* --- MAIN VIEWER & STATUS BAR (Viewport and Footer) --- */\n"
"/* Central widget where the image is displayed */\n"
"QGraphicsView, QLabel#ImagePreview {\n"
"    background-color: #e6e6e6; /* Light gray for viewing area */\n"
"    border: 1px dashed #cccccc; /* Light border for the drag and drop box */\n"
"}\n"
"\n"
"/* Footer Bar/Status Bar */\n"
"QStatusBar {\n"
"    background-color: #e6e6e6;\n"
"    color: #555555;\n"
"    border-top: 1px solid #cccccc;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"/* --- SETTINGS PANEL (Right Collapsible Panel) --- */\n"
"/* Assuming the right panel uses QWidget or QScrollArea */\n"
"QScrollArea, QWidget#SettingsPanel {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: none;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #1e1e1e;\n"
"    border: none;\n"
"    padding: 5px 0;\n"
"}\n"
"\n"
"/* --- INPUTS (Sliders, Text Fields, Checkboxes) --- */\n"
"QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    color: #1e1e1e;\n"
"}\n"
"\n"
"/* Sliders (e.g., Confidence, Noise Reduction) */\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #cccccc;\n"
"    height: 8px; /* height of the groove */\n"
"    background: #e0e0e0;\n"
"    margin: 2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #0078d4; /* Accent color */\n"
"    border: 1px solid #0078d4;\n"
"    width: 12px;\n"
"    margin: -3px 0; /* center the handle vertically */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Radio Buttons and Checkboxes */\n"
"QRadioButton::indicator, QCheckBox::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"    border: 1px solid #999999;\n"
"    background-color: #ffffff;\n"
"}\n"
"QRadioButton::indicator:checked, QCheckBox::indicator:checked {\n"
"    background-color: #0078d4; /* Checked state accent */\n"
"    border: 1px solid #0078d4;\n"
"}\n"
"\n"
"/* --- COMBO BOXES/DROPDOWNS --- */\n"
"QComboBox {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 5px;\n"
"    border-radius: 4px;\n"
"    color: #1e1e1e;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"}\n"
"\n"
"/* --- GROUP BOXES (For tool organization) --- */\n"
"QGroupBox {\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex; /* leave space at the top for the title */\n"
"    background-color: #fcfcfc;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; \n"
"    padding: 0 3px;\n"
"    color: #555555;\n"
"    background-color: #fcfcfc;\n"
"}\n"
"\n"
"#fileMgtLabel, #processingToolsLabel {\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#dimsLabel, #imageDimensionsLabel {\n"
"    font-size: 7.5pt;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        ImageLab.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(ImageLab)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fileMgtLabel = QtWidgets.QLabel(self.horizontalFrame)
        self.fileMgtLabel.setObjectName("fileMgtLabel")
        self.verticalLayout_2.addWidget(self.fileMgtLabel)
        self.UploadButton = QtWidgets.QPushButton(self.horizontalFrame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/upload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UploadButton.setIcon(icon)
        self.UploadButton.setObjectName("UploadButton")
        self.verticalLayout_2.addWidget(self.UploadButton)
        self.pushButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line_2 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.processingToolsLabel = QtWidgets.QLabel(self.horizontalFrame)
        self.processingToolsLabel.setObjectName("processingToolsLabel")
        self.verticalLayout_3.addWidget(self.processingToolsLabel)
        self.resizeBtn = QtWidgets.QPushButton(self.horizontalFrame)
        self.resizeBtn.setObjectName("resizeBtn")
        self.verticalLayout_3.addWidget(self.resizeBtn)
        self.obj_detectionBtn = QtWidgets.QPushButton(self.horizontalFrame)
        self.obj_detectionBtn.setObjectName("obj_detectionBtn")
        self.verticalLayout_3.addWidget(self.obj_detectionBtn)
        self.filtersBtn = QtWidgets.QPushButton(self.horizontalFrame)
        self.filtersBtn.setObjectName("filtersBtn")
        self.verticalLayout_3.addWidget(self.filtersBtn)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalFrame_4 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.verticalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.processed_image_page = QtWidgets.QWidget()
        self.processed_image_page.setObjectName("processed_image_page")
        self.stackedWidget.addWidget(self.processed_image_page)
        self.original_image_page = QtWidgets.QWidget()
        self.original_image_page.setObjectName("original_image_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.original_image_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ImagePreview = QtWidgets.QGraphicsView(self.original_image_page)
        self.ImagePreview.setObjectName("ImagePreview")
        self.gridLayout_2.addWidget(self.ImagePreview, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dimsLabel = QtWidgets.QLabel(self.original_image_page)
        self.dimsLabel.setObjectName("dimsLabel")
        self.horizontalLayout_3.addWidget(self.dimsLabel)
        self.imageDimensionsLabel = QtWidgets.QLabel(self.original_image_page)
        self.imageDimensionsLabel.setText("")
        self.imageDimensionsLabel.setObjectName("imageDimensionsLabel")
        self.horizontalLayout_3.addWidget(self.imageDimensionsLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.original_image_page)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.verticalFrame_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.selectStandardZoomComboBox = QtWidgets.QComboBox(self.verticalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectStandardZoomComboBox.sizePolicy().hasHeightForWidth())
        self.selectStandardZoomComboBox.setSizePolicy(sizePolicy)
        self.selectStandardZoomComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.selectStandardZoomComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectStandardZoomComboBox.setObjectName("selectStandardZoomComboBox")
        self.horizontalLayout_5.addWidget(self.selectStandardZoomComboBox)
        self.zoomInButton = QtWidgets.QPushButton(self.verticalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomInButton.sizePolicy().hasHeightForWidth())
        self.zoomInButton.setSizePolicy(sizePolicy)
        self.zoomInButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.zoomInButton.setObjectName("zoomInButton")
        self.horizontalLayout_5.addWidget(self.zoomInButton)
        self.zoomOutButton = QtWidgets.QPushButton(self.verticalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomOutButton.sizePolicy().hasHeightForWidth())
        self.zoomOutButton.setSizePolicy(sizePolicy)
        self.zoomOutButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.horizontalLayout_5.addWidget(self.zoomOutButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_8.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.verticalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_8.addWidget(self.pushButton_13)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addWidget(self.verticalFrame_4)
        self.verticalLayout_5.addWidget(self.horizontalFrame)
        self.horizontalFrame_6 = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_9.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.horizontalFrame_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.statusLabel = QtWidgets.QLabel(self.horizontalFrame_6)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_6.addWidget(self.statusLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_5.addWidget(self.horizontalFrame_6)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        ImageLab.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImageLab)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTheme = QtWidgets.QMenu(self.menuView)
        self.menuTheme.setObjectName("menuTheme")
        ImageLab.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImageLab)
        self.statusbar.setObjectName("statusbar")
        ImageLab.setStatusBar(self.statusbar)
        self.SettingsPanel = QtWidgets.QAction(ImageLab)
        self.SettingsPanel.setObjectName("SettingsPanel")
        self.actionSave = QtWidgets.QAction(ImageLab)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(ImageLab)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionDark = QtWidgets.QAction(ImageLab)
        self.actionDark.setObjectName("actionDark")
        self.actionLight = QtWidgets.QAction(ImageLab)
        self.actionLight.setObjectName("actionLight")
        self.menuFile.addAction(self.SettingsPanel)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuTheme.addAction(self.actionDark)
        self.menuTheme.addAction(self.actionLight)
        self.menuView.addAction(self.menuTheme.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(ImageLab)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ImageLab)

    def retranslateUi(self, ImageLab):
        _translate = QtCore.QCoreApplication.translate
        ImageLab.setWindowTitle(_translate("ImageLab", "Compter Vision Lab"))
        self.fileMgtLabel.setText(_translate("ImageLab", "File Management"))
        self.UploadButton.setText(_translate("ImageLab", "Upload Image"))
        self.pushButton.setText(_translate("ImageLab", "Recent Files"))
        self.pushButton_3.setText(_translate("ImageLab", "Save"))
        self.pushButton_4.setText(_translate("ImageLab", "Save As"))
        self.processingToolsLabel.setText(_translate("ImageLab", "Processing Tools"))
        self.resizeBtn.setText(_translate("ImageLab", "Resize/Aspect Ratios"))
        self.obj_detectionBtn.setText(_translate("ImageLab", "Object Detection"))
        self.filtersBtn.setText(_translate("ImageLab", "Filters/Enhancements"))
        self.dimsLabel.setText(_translate("ImageLab", "Image dimensions:"))
        self.label_3.setText(_translate("ImageLab", "Zoom:"))
        self.zoomInButton.setText(_translate("ImageLab", "+"))
        self.zoomOutButton.setText(_translate("ImageLab", "-"))
        self.pushButton_12.setText(_translate("ImageLab", "Undo"))
        self.pushButton_13.setText(_translate("ImageLab", "Redo"))
        self.label_4.setText(_translate("ImageLab", "Status:"))
        self.menuFile.setTitle(_translate("ImageLab", "File"))
        self.menuView.setTitle(_translate("ImageLab", "View"))
        self.menuTheme.setTitle(_translate("ImageLab", "Theme"))
        self.SettingsPanel.setText(_translate("ImageLab", "Open..."))
        self.actionSave.setText(_translate("ImageLab", "Save"))
        self.actionSave_As.setText(_translate("ImageLab", "Save As..."))
        self.actionDark.setText(_translate("ImageLab", "Dark"))
        self.actionLight.setText(_translate("ImageLab", "Light"))
from resources import resources_rc
