# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\dev\cv\uidesigns\object_detection_tools_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ObjectDetectionTool(object):
    def setupUi(self, ObjectDetectionTool):
        ObjectDetectionTool.setObjectName("ObjectDetectionTool")
        ObjectDetectionTool.resize(272, 253)
        self.gridLayout = QtWidgets.QGridLayout(ObjectDetectionTool)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.boundinBoxPreviewCheckbox = QtWidgets.QCheckBox(ObjectDetectionTool)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boundinBoxPreviewCheckbox.sizePolicy().hasHeightForWidth())
        self.boundinBoxPreviewCheckbox.setSizePolicy(sizePolicy)
        self.boundinBoxPreviewCheckbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.boundinBoxPreviewCheckbox.setObjectName("boundinBoxPreviewCheckbox")
        self.verticalLayout_8.addWidget(self.boundinBoxPreviewCheckbox)
        self.line_2 = QtWidgets.QFrame(ObjectDetectionTool)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_8.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ObjectDetectionTool)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(ObjectDetectionTool)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(ObjectDetectionTool)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_8.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(ObjectDetectionTool)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/eye.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(ObjectDetectionTool)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/web.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 1, 1)

        self.retranslateUi(ObjectDetectionTool)
        QtCore.QMetaObject.connectSlotsByName(ObjectDetectionTool)

    def retranslateUi(self, ObjectDetectionTool):
        _translate = QtCore.QCoreApplication.translate
        ObjectDetectionTool.setWindowTitle(_translate("ObjectDetectionTool", "Object Detection Tool"))
        self.boundinBoxPreviewCheckbox.setText(_translate("ObjectDetectionTool", "Show Bounding Boxes on Preview"))
        self.label.setText(_translate("ObjectDetectionTool", "Confidence Threshhold"))
        self.pushButton.setText(_translate("ObjectDetectionTool", "Preview"))
        self.pushButton_2.setText(_translate("ObjectDetectionTool", "Generate HTML"))
from resources import resources_rc
